
public class Settings {
	
	// number of players playing the game
	static int numPlayers = 5;
	
	// total numbers to be generated by the moderator
	static int totNumGenerate = 10;
	
	// total numbers to be in the ticket of each player
	static int totTicketNum = 10;
	
	// max value that the generated number can take
	static int maxValue = 50;
	
	// min value that the generated number can take
	static int minValue = 1;
	
	// number of matches required of a winning player
	static int numMatches = 3;
	
	// time the moderator gives to other player for checking their numbers
	static int waitTime = 1000;
}
